version: "3"
services:
  aerospike:
     image: aerospike/aerospike-server:latest
     ports:
       - 3000:3000
     labels:
       - "com.aerospike.cluster=ratelimiter"
     environment:
       - "affinity:com.aerospike.cluster!=ratelimiter"

  redis:
#      image: redis:4.0-alpine
      image: grokzen/redis-cluster
      ports:
      - '7000-7007:7000-7007'
      environment:
        - IP=0.0.0.0
        - STANDALONE=true
